### ISSUE TITLE
Multiple objects with same value of primary key field.

### ISSUE THREAD

**Issue by AlloyDev** [EasyMapping/EasyMapping#103]
I've got object with children of the same class. I wrote mapping and set primary keys.
Here is my mapping: https://gist.github.com/AlloyDev/c59a0e40dbd0fd0e9c52
I map objects with `+ (NSArray *)arrayOfObjectsFromExternalRepresentation:(NSArray *)externalRepresentation
                                          withMapping:(EKManagedObjectMapping *)mapping
                               inManagedObjectContext:(NSManagedObjectContext*)context` method. 

For some reason I received objects with same `clusterId` field.

**Comment by DenHeadless** [comment]
You don't actually need separate mapping for recursive mappings - they are supported out of the box. You can simply call following:

```objective-c
[mapping hasMany:[RNDCluster class] forKeyPath:@"related" forProperty:@"childClusters"];
```

**Comment by AlloyDev** [comment]
It was my first implementation. In that case I also have multiply clusters with same `clusterId`. One with `clusterBody` and `childClusters` and one without.
I think that this may be due to some clusters could be root cluster and also a child cluster for other root clusters.

**Comment by DenHeadless** [comment]
I'm not sure what is the issue here. Is the data in objects different(except for clusterId)? 

Can you post an example of your JSON?

**Comment by AlloyDev** [comment]
Wrote small test project: https://github.com/AlloyDev/EasyMappingIssue103
As you can see cluster 30637176 duplicates

**Comment by AlloyDev** [comment]
Resolved issue via manual mapping `withValueBlock` for related clusters. But also we need to create mapping for related clusters without mapping related clusters, children of some root clusters will be overwritten otherwise.
Updated test repo: https://github.com/AlloyDev/EasyMappingIssue103
And gist: https://gist.github.com/AlloyDev/c59a0e40dbd0fd0e9c52

**Comment by MLSDev** [comment]
I'm not sure i understand the issue here.

1. Your JSON contains duplicate entries for clusterId - 30637176 and 30645762 exist on parent and on child level
2. What happens from MagicalRecord standpoint, is when you call MR_deleteAllMatchingPredicate, it selects following objects - http://d.pr/i/eLGq, which results in deleting every single RDNCluster object

**Comment by DenHeadless** [comment]
I'm not sure i understand the issue here.

1. Your JSON contains duplicate entries for clusterId - 30637176 and 30645762 exist on parent and on child level
2. What happens from MagicalRecord standpoint, is when you call MR_deleteAllMatchingPredicate, it selects following objects - http://d.pr/i/eLGq, which results in deleting every single RDNCluster object

**Comment by AlloyDev** [comment]
1. Yes, problem is here. I thought, that everything is ok and manual mapping works fine, but sometimes it breaks on real data. The issue is EM creates objects with same **primary key** in case same objects on parent and child level.
2. Everything is ok here, I just tested deleting and forgot to remove this check.

**Comment by DenHeadless** [comment]
Are you saying that example project does not have this issue?

We need to replicate this behaviour to write a reliable test. Can you narrow down on which JSON you are getting this?

**Comment by AlloyDev** [comment]
Yes, I thought that I had solution.
To present I resolve issue by mapping all fields except `related` via EM and then just set parent-child relations manually. Also I wrote test for it in project.
Example of test: https://gist.github.com/AlloyDev/438405e7dfd007784317
Json for test: https://gist.github.com/AlloyDev/ae2e38fe1fccdb027a2f

**Comment by DenHeadless** [comment]
Can you update example project with this code?

**Comment by AlloyDev** [comment]
Updated project. There are three common implementations in RDNCluster+RDNMapping except manually adding parent-child relations.

**Comment by DenHeadless** [comment]
Thanks you for taking time and making detailed example and tests.

I have spent some time researching this stuff, but it seems you have duplicated clusterID's once again in your JSON - http://d.pr/i/qaXf

It's not clear how EasyMapping would even deal with these kinds of JSON. Even if we were caching objects before their full initialization, behavior would still be incorrect - you would be replacing parent object content with the child one.

It seems you are having issue with your back-end, not with EasyMapping. You probably should not get duplicated clusterID on children objects in the way you are receiving.

I'm closing this issue for now, cause it seems EasyMapping if behaving correctly( or at least reasonable, given this kind of JSON). 

Feel free to reopen this issue or create a new one, if there is duplication in different scenarios.
