### ISSUE TITLE
Bool from string parsing

### ISSUE THREAD

**Issue by ivan-golub** [EasyMapping/EasyMapping#104]
Im getting -[__NSCFString charValue]: unrecognized selector sent to instance 0x7b160510
when trying to parse @"true" to BOOL property. Any workarounds except custom mapping?

**Comment by DenHeadless** [comment]
EasyMapping uses simple KVC for setting properties, therefore setting NSString to BOOL property causes crash, which is expected.

You can parse such properties using mapKeyPath:toProperty:withValueBlock: method.

Consider asking your back-end developer for a reason, why boolean property is sent as string in JSON =)
