### ISSUE TITLE
Does not work in Swift.

### ISSUE THREAD

**Issue by czaku** [EasyMapping/EasyMapping#105]
I am trying to follow your Swift examples, tried many ways, with EKMappingProtocol, with EKObjectModel and keep receiving "setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key someRandomKey.'"

Any help appreciated

**Comment by DenHeadless** [comment]
This means you don't have someRandomKey property on your class. That is as much as i can say without seeing mapping and class interface

**Comment by czaku** [comment]
My class is literally copy paste of your Car and Person examples and does have 'var someRandomKey: Int!' property

**Comment by lucasmedeirosleite** [comment]
I use it with swift and it works fine!
Are using inheritence or the protocol on your models?

**Comment by czaku** [comment]
In the initial question I wrote that i tried with Protocol and with inheritance.

This is my class now:

```swift
import Foundation

@objc class PrivacyNotificationsResponseObject: EKObjectModel {
    var hasFacebookPostPermission: Int!
    var privacySettings: [PrivacyNotificationObject]!
    var notificationSettings: [PrivacyNotificationGroupObject]!
}

extension PrivacyNotificationsResponseObject {
    override class func objectMapping() -> EKObjectMapping! {
        var mapping = EKObjectMapping(objectClass: self)
        mapping.mapPropertiesFromDictionary(["has_facebook_post_permission" : "hasFacebookPostPermission"]);
        mapping.hasMany(PrivacyNotificationObject.self, forKeyPath: "privacy_settings", forProperty: "privacySettings")
        mapping.hasMany(PrivacyNotificationObject.self, forKeyPath: "notification_settings", forProperty: "notificationSettings")
        return mapping
    }
}
```

**Comment by czaku** [comment]
Just adding a bit, my project is Objective-C project that I have started using with Swift code, the parsing is called in Objective-C
```Swift
PrivacyNotificationsResponseObject *privacyNotificationsResponseObject = 
[EKMapper objectFromExternalRepresentation:responseObject withMapping:[PrivacyNotificationsResponseObject objectMapping]];
```

It is crashing on method

```Objective-C
+(void)setValue:(id)value onObject:(id)object forKeyPath:(NSString *)keyPath
{
    if ([(id <NSObject>)object isKindOfClass:[NSManagedObject class]])
    {
        // Reducing update times in CoreData
        id _value = [object valueForKeyPath:keyPath];
        
        if (_value != value && ![_value isEqual:value]) {
            [object setValue:value forKeyPath:keyPath];
        }
    }
    else {
       //CRASHING IN THE LINE BELOW
        [object setValue:value forKeyPath:keyPath];
    }
}
```

Crash is: ....PrivacyNotificationsResponseObject 0x1742593b0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key hasFacebookPostPermission.'
So in this method keyPath is nil, but the method that calls 
```Objective-C
+(void)setValue:(id)value onObject:(id)object forKeyPath:(NSString *)keyPath
```
does not have that nil ...

**Comment by czaku** [comment]
Ok guys issue solved! 
When mixing Objective-C and Swift EasyMapping for me requires to be using Objective-C types, so the example class Car would be

```Swift
class Car: EKObjectModel {
    var model : NSString!
    var year : NSString!
    var createdAt : NSDate!
}

extension Car {
    override class func objectMapping() -> EKObjectMapping{
        var mapping = EKObjectMapping(objectClass: self)
        mapping.mapPropertiesFromArray(["model","year"])
        return mapping
    }
}
```

So NSString, NSNumber etc. instead of Swift String, Int ...
