### ISSUE TITLE
IOS 8.3 + Error [__NSCFString unsignedLongLongValue]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by ufsergey** [EasyMapping/EasyMapping#106]
Then i use @property (nonatomic,assign) NSUInteger conversation_id and using mapping [mapping mapPropertiesFromDictionary:@{@"conversation_id":@"conversation_id"}]; Error is " [__NSCFString unsignedLongLongValue]: unrecognized selector sent to instance " in IOS 8.3+ . There is no errors in previos versions of iOS (8.2 <) .

**Comment by florianbuerger** [comment]
Can you post the JSON for this? Seems like the `conversion_id` inside your JSON is a string. It must be a number or you have to provide a block to convert the string.

**Comment by DenHeadless** [comment]
I'm closing this issue until more info is provided.
