### ISSUE TITLE
mapping a JSON structure with dynamic key names

### ISSUE THREAD

**Issue by beribas** [EasyMapping/EasyMapping#108]
Hi folks,

I have been using EasyMapping for a few months now and was happy so far with its light and easy usage. 
I encountered one issue with the following JSON structure:

```javascript
{
 "coordinates": {
    "Portugal": {
      "city_located": [
      ...
      ],
      "country_located": [
      ...
      ],
      "street_located": [
      ...
      ]
    },
    "Spain": {
      "city_located": [
      ...
      ],
      "country_located": [
      ...
      ],
      "street_located": [
      ...
      ]
    }
  }
}
```

which I'd like to map on Objects like (just example):
```Objective-C
@interface CoordinateCluster
@property NSString *countryName;
@property NSArray *cityLocated;
...
@end
```

Is there a way to achieve this with EasyMapping? The problem is that I have to assign the key (e.g. "Portugal") to one property of object and the value to the others.
I also have doubts if such a JSON structure is well. 
I'd be thankful for any help or advice!

**Comment by DenHeadless** [comment]
Hi!
Sorry for long response, i somehow missed this issue, and found it accidentally today.

Basically, if you really need this data structure, i would go with valueBlock mapping on coordinate level, something like this:

```
[mapping mapKeyPath:@"coordinate" toProperty:@"coordinate" withValueBlock:^id(NSString * key, id value) {
     CoordinateCluster * cluster = [CoordinateCluster new];
     cluster.countryName = key;
     cluster.cityLocated = value[@"city_located"];
    return cluster;
}];
```

Maybe i'm missing something, but it seems like an easiest way.

**Comment by NBibikov** [comment]
Thank you very much for response! It's work!
Unfortunately i can not change API

**Comment by beribas** [comment]
Thank you, Dan! 

Well, the problem is actually a little bigger since the "city_located" array also contains structures which have to be mapped. However, I used similar approach to solve the problem and it works.
