### ISSUE TITLE
Value from subDictionary without name

### ISSUE THREAD

**Issue by NBibikov** [EasyMapping/EasyMapping#109]
Hello again and thanks again for great library. I enjoy work with EasyMapping. Really!
But now i have one trouble. I have next JSON:
```
{
    "__v" = 0;
    "_id" = 55d5e42d201308a16859f9cf;
    body = "new message 1";
    date = "20-08-2015 17:29:01";
    ident =     (
                {
            status = 0;
            userIdFor = 58;
        }
    );
    nickname = "Matt Galloway";
    num = 0;
    roomid = "wf_Ijsgczv";
    userid = 81;
}
```

How i can get 'status' and 'userIdFor' when dictionary in "indent" Array doesn't has name?

**Comment by DenHeadless** [comment]
Hi @NBibikov!

The answer here is that we depend on KVC capabilities, that are used for mapping. We use valueForKeyPath: and setValue:forKeyPath: methods to perform mapping. Therefore everything that can be expressed in KVC can be used in mapping.

I haven't tried this, but you can try following:

```
[mapping mapKeyPath:@"ident.status.@firstObject" toProperty:@"status"];
```

If this doesn't work, try playing with KVC more, you basically need some form of valueForKeyPath: call that will return you status or userIdFor value. If this doesn't work, consider putting ident into separate property on your object and use mapWithValueBlock: method.

**Comment by NBibikov** [comment]
Yes. this is work! Thank you very much!!!

**Comment by NBibikov** [comment]
I have other situation: how i can get second dictionary?

**Comment by DenHeadless** [comment]
lastObject? =) I don't know any other KVC operator that could help here. It's probably better to have separate object.
