### ISSUE TITLE
What if object doesn't exist in some responses?

### ISSUE THREAD

**Issue by NBibikov** [EasyMapping/EasyMapping#111]
Hi! I have JSON with different responses - in some object exist, in other - no. Is it possible to resolve with EasyMapping? Thanks.

```
{
    ID = 46;
    acf =     (
    );
```
```
{
    ID = 178;
    acf =     {
        imageforcategory = "http://site.com/wp-content/uploads/2015/09/image.jpg";
    };

```

*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<__NSCFBoolean 0x36c0f60> valueForUndefinedKey:]: this class is not key value coding-compliant for the key imageforcategory.'

**Comment by DenHeadless** [comment]
It's safe to have a nil property on your object as long as the structure of JSON is the same. I believe that crash you are having is not because object is not there, but because mapping is not entirely correct, or JSON structure is different.

**Comment by NBibikov** [comment]
Thanks for quick reply!
is that not a problem for the library, that in one case returns an array with the object, and the other without? is it not a violation of the structure?

**Comment by DenHeadless** [comment]
It depends on the mapping, however in most cases this is not a problem. Property will simply be nil.

**Comment by NBibikov** [comment]
Ok. Thanks I'll be looking this bug

**Comment by DenHeadless** [comment]
I'll close issue for now, please reopen it, if there's some issue with library.

**Comment by NBibikov** [comment]
No, it seems EasyMapping cannot write an object that does not exist
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unacceptable type of value for attribute: property = "imageforcategory"; desired type = NSString; given type = __NSArrayI; value = (
).'
*** First throw call stack:
(
	0   CoreFoundation                      0x0345c746 __exceptionPreprocess + 182
	1   libobjc.A.dylib                     0x030e5a97 objc_exception_throw + 44
	2   CoreData                            0x006d9ffe _PFManagedObject_coerceValueForKeyWithDescription + 3454
	3   CoreData                            0x006ab8dd _sharedIMPL_setvfk_core + 205
	4   CoreData                            0x006d9226 -[NSManagedObject(_PFDynamicAccessorsAndPropertySupport) _setGenericValue:forKey:withIndex:flags:] + 54
	5   CoreData                            0x006c7e6c _PF_Handler_Public_SetProperty + 108
	6   CoreData                            0x006c7dd5 -[NSManagedObject setValue:forKey:] + 181
	7   Foundation                          0x00e8b016 -[NSObject(NSKeyValueCoding) setValue:forKeyPath:] + 386
	8   AlmazInUa                           0x00212e3d +[EKPropertyHelper setValue:onObject:forKeyPath:] + 317
	9   AlmazInUa                           0x00212c4c +[EKPropertyHelper setProperty:onObject:fromRepresentation:inContext:respectPropertyType:] + 796
	10  AlmazInUa                           0x00207441 __75-[EKManagedObjectMapper fillObject:fromExternalRepresentation:withMapping:]_block_invoke + 289
	11  CoreFoundation                      0x0338b01a __65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 106
```

**Comment by DenHeadless** [comment]
From this call stack I would say that you have NSString property and you receive NSArray. And CoreData throws an exception about this.
