### ISSUE TITLE
How to map array of strings?

### ISSUE THREAD

**Issue by Sh1mor1nka** [EasyMapping/EasyMapping#114]
Hello, i'm new in EasyMapping, i need to map array of strings to CoreData, key - "photos", how can i do this? In my xcdatamodeld i create key with NSData type i hope i can map array to NSData, or i can't? Or there are some other ways? Thank you!

```code
{
     id: 262,
     title: 'Fort Hamilton',
     photos : [
                   'http://url//locations/47/photo/ab/db/eb/4d/2122/photo_2122.jpg',
                   'http://url//locations/47/photo/5a/1e/3a/5a/2123/photo_2123.jpg'
               ]
}
```

UDP:
and can i map such JSON
```
{
street: 'bla',
city: 'bla bla',
coordinates:{
           lat : 12345,
           lon: 12345
       }
}
```

like this
```
+(EKManagedObjectMapping *)addressMapping {
    return [EKManagedObjectMapping mappingForEntityName:NSStringFromClass([Address class]) withBlock:^(EKManagedObjectMapping *mapping) {
        [mapping mapPropertiesFromArray:@[@"street", @"city"]];
// i don't want to create new NSManagedObject to store my "lat" and "lon", can i do this trick?
        [mapping mapKeyPath:@"coordinates.lat" toProperty:@"latitude"];
        [mapping mapKeyPath:@"coordinates.lon" toProperty:@"longitude"];
    }];
}
```
thank you!

**Comment by Sh1mor1nka** [comment]
Okay, i find smth useful, to store array as NSData i can do
```
[mapping mapKeyPath:@"photos" toProperty:@"photos" withValueBlock:^id(NSString *key, id value, NSManagedObjectContext *context) {
            NSData *data = [NSKeyedArchiver archivedDataWithRootObject:[NSArray arrayWithArray:value]];
            return data;
        }];
```

**Comment by DenHeadless** [comment]
```objectivec
[mapping mapKeyPath:@"coordinates.lat" toProperty:@"latitude"];
```
Yes, you can.

As for image urls, you can of course use NSKeyedArchiver, but it would probably be better to create one-to-many relationship and store urls as strings.

**Comment by Sh1mor1nka** [comment]
Thank you very much Denis! I have last question for you :)
Should i register all mapping or it's doing automatically? In example you swap because of different mappings.

**Comment by DenHeadless** [comment]
Mapping is dynamic, so when new data model is received, mapping object is created. Basically you can simply inherit from EKObjectModel or EKManagedObjectModel in case of CoreData, and have mapping in objectMapping method and that's it.

The swapping stuff is only needed when you have different mapping models and is basically a workaround for EasyMapping unit tests =) Usually in your application, you would have only one mapping needed for data model.

**Comment by Sh1mor1nka** [comment]
Dear Den, sorry but it's me again :)
Is there any tool in EasyMapping to replace or delete objects from CoreData?
Thank you!

**Comment by DenHeadless** [comment]
EasyMapping provides mapping, not managing CoreData objects, however it does have method on EKManagedObjectMapper that allows to sync CoreData arrays. It also has incrementalData option on EKObjectMapper, that defines, whether objects will be replaced, or added on top of previous ones.

I think that's about it with EasyMapping and CoreData.
