### ISSUE TITLE
Object can't have two owners?

### ISSUE THREAD

**Issue by Sh1mor1nka** [EasyMapping/EasyMapping#118]
I have two different objects witch can own the same object.

response 1 for MyManagedObject
```
[
	{
		id: 3,
		cat: {
			id: 1 // id the same
		}
	}
...
]
```
response 2 for MyOtherManagedObject
```
[
	{
		id: 15,
		cat: {
			id: 1 // id the same
		}
	}
...
]
```

cat has "id" as primary key, so will my two NSManagedObjects have objects "cat" or no? Because i have strange issue now, i have many objects with cats inside, but one dog has nil cat, i think that somewhere was created cat with the same id so new one wasn't created and my object doesn't has cat, or reference on cat, am i right? Thank you.

**Comment by DenHeadless** [comment]
JSON you posted is invalid, you can't have dictionary with same keys on the same level. 

Anyway, multiple owners are of course supported if you are mapping into CoreData. If you have object in original JSON, you should have object after mapping operation.

**Comment by Sh1mor1nka** [comment]
Sorry for poor JSON, i have updated it, i forget to say that i map in to CoreData, may be i need to set some other properties for relationship?
![screen shot 2015-10-30 at 21 33 54](https://cloud.githubusercontent.com/assets/2759167/10856101/0afbf22a-7f4e-11e5-95da-ec8bd523b7dc.png)

**Comment by DenHeadless** [comment]
I'm not sure, but you should get reference to the same object in CoreData, not nil.

**Comment by Sh1mor1nka** [comment]
well, if i remove primaryKey my cat creates, but as i understand it creates twice...

**Comment by Sh1mor1nka** [comment]
well the problem was in inverse relationship, i don't understand why, but after i removed inverse my object has two owners, i check memory references on both objects, they were the same.

P.S. You can close issue, if you have any assumptions, say it, thank you.

**Comment by Sh1mor1nka** [comment]
UDP: Hah! Problem was not in inverse relationship! Problem was that my inverse relationship was "to one", so i can have only one owner, i put back all my inverse relationships and made them "to many" and it's working! Thank you!

**Comment by DenHeadless** [comment]
Oh, indeed) Probably when CoreData sees One-To-One Relationship, it replaces old one instead of creating relationship.
