### ISSUE TITLE
Combine multiple key paths into one property

### ISSUE THREAD

**Issue by Rusik** [EasyMapping/EasyMapping#120]
I have data like this:
```
[
    {
    "id" : 1,
    "data" : "some data"
    "locale" : "en",
    "name" : "foo"
    }, ...
]
```

I need to create two model objects from this. One should link to another: `object -> object translation`
```
object : { "object id": 1, "data" : "some data" } 
object translation : { "object translation id" : "1_en", "name" : "foo"}
```

So for `object translation id` I should combine two key paths from dictionary `id + locale `. I can't understand how to do it with existing methods of `EKObjectMapping` :(

**Comment by DenHeadless** [comment]
Seems like you have two options: 

1. Use mapKeyPathToProperty:withValueBlock:
2. Override initWithProperties:, and just create your object as usual.

I understand both of those are not really convenient, however with that JSON structure it's really hard to propose something different, even with different mappers, not only EasyMapping =)
