### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by ilyapuchka** [EasyMapping/EasyMapping#84]
Do we need any validation during mapping? Like getting error back from EKMapper with list of invalid keys and values?

**Comment by DenHeadless** [comment]
I don't think we do. Mapping should work safely, or raise exceptions when keys are invalid. What would you do with information, that for example list of keys are invalid? And how would you mark them as invalid?

However, i'm open for discussion, making EasyMapping more safe and functional is always my goal.

**Comment by ilyapuchka** [comment]
At least we can leave invalid properties with nil values. Also we can even not create object if it's representation is invalid and we check for it at first. Maybe it could make core data import faster, though I din't work with EasyMapping + CoreData. I think in terms of mapping it's better to have no object than to have invalid one as a result. Of course in mapping block user can provide default value if input is not valid, check for input value type and transform it to appropriate one and do what ever else, but maybe it's not what users would like to do and maybe we can simplify this task. Also for me to provide some error as feedback of some failable operation is a good practice. If you have an error after mapping object you can ignore this object or log this error in your logging system or provide any fallback in your application. And you just check the error message, not all properties of result object that you are interested in and that should be correct to use this object further. Hope you'll got my point =)

**Comment by DenHeadless** [comment]
Yes, returning NSError from Foundation API is a common practice. However with mapping, too much stuff can go off rails, it does not seems possible to cover all cases. Wrapping everything in try catches, and endless if's seems not efficient. 

It would be nice to fail gracefully and provide keys or values, that are unexpected, but i'm not sure if we can achieve this in a clean and compact way.

**Comment by mitrenegade** [comment]
does easymapping handle uniqueness validation? Do I have to fetch an existing object based on id in order to update it? How does this affect the benchmarking, say if I had to update hundreds of records?

**Comment by DenHeadless** [comment]
Hi!

CoreData.framework supports uniqueness by using primary key on your NSManagedObject. Of course, you need to fetch object prior to updating it. 

EasyMapping implements some optimizations, that will speed up imports of large number of objects in CoreData. If you have performance issues, I suggest profiling them with Instruments to actually see where your performance problem is.

Best regards,
                     Denys Telezhkin

**Comment by DenHeadless** [comment]
Closing this issue for now, cause it's a discussion, not an issue for EasyMapping.
