### ISSUE TITLE
Is it possible to make "primaryKey" in EKManagedObjectMapping optional?

### ISSUE THREAD

**Issue by i3th** [EasyMapping/EasyMapping#88]
HI! 
I have very simple object without ID or any unique field. 
How can I skip setting primary key to mapping?

**Comment by DenHeadless** [comment]
Hi! 
Having primary key is optional already. What makes you think it is required?

**Comment by i3th** [comment]
Exception is raised if primary key is not set.

Here is my model
![screen shot 2015-02-12 at 10 33 41](https://cloud.githubusercontent.com/assets/1662930/6163511/6215f258-b2a4-11e4-9e58-40a1038b5870.png)
Lesson Mapping

     + (EKManagedObjectMapping *)objectMapping {
       return [EKManagedObjectMapping mappingForEntityName:@"MOLesson" withBlock:^(EKManagedObjectMapping *mapping) {
         [mapping mapPropertiesFromArray:@[@"textLength", @"title", @"uid", @"orderNumber"]];
       }];
     }

JSON. Course as root object contains lessons

    {"textLenght": "4 min",
     "lessons": [
                {"orderNumber": 0,
                "textLenght": "4 min",
                "title": "Title 0"}
                ],
    "title": "Introducing the global financial markets",
    }
In [EKCoreDataImporter cacheObject: withMapping:] file I got exception because mapping.primaryKey is nil

    -(void)cacheObject:(NSManagedObject *)object withMapping:(EKManagedObjectMapping *)mapping
    {
        NSMutableDictionary *entityObjectsMap = self.fetchedExistingEntities[mapping.entityName];
        entityObjectsMap[[object valueForKey:mapping.primaryKey]] = object; // but mapping.primaryKey is nil
        self.fetchedExistingEntities[mapping.entityName] = entityObjectsMap;
    }

**Comment by DenHeadless** [comment]
This was a bug that was fixed in 0.12.1 release, specifically in 7fba949f902c73890d42bce190e59a5a3513d694. Please try it, probably should work fine.
