### ISSUE TITLE
nil values need to replace existing values for dates

### ISSUE THREAD

**Issue by mitrenegade** [EasyMapping/EasyMapping#91]
When I create a date mapper, if the json contains an explicit null value for that property, dates currently don't replace the existing value with a null value. This may be true of other mappings too, but I've explicitly tested it for when we have a date.

**Comment by DenHeadless** [comment]
Fixed by 26c887782a068e12724889550255112190039e34

**Comment by DenHeadless** [comment]
I've released [0.13.0 version](https://github.com/EasyMapping/EasyMapping/releases/tag/0.13.0) with this fix.
