### ISSUE TITLE
EKMapper retaining objects

### ISSUE THREAD

**Issue by fnxpt** [EasyMapping/EasyMapping#94]
Hi guys,

Just notice that the following method is retaining the objects, do you have the same issue?
+[EKMapper objectFromExternalRepresentation:withMapping:]

Kind Regards,
fnxpt

**Comment by DenHeadless** [comment]
What makes you think that? And what objects are retained? 

We are using ARC, and the only way to have memory problems on ARC is to have retain cycles, and i don't see any here.

Please feel free to reopen this issue, if there really is a problem.
