### ISSUE TITLE
hasMany with ids

### ISSUE THREAD

**Issue by bilby91** [EasyMapping/EasyMapping#95]
Hello,

I'm planning to implement a Relation to support array of ids.

```
{
  "id": 1,
  "category_ids" : [ 1, 2, 3, 4]
}
```

Any special consideration for an API like this. Any preference ? 

Thanks!

**Comment by DenHeadless** [comment]
You can map those to simple NSArray, that is as much as I can tell without seeing actual task and architecture. Please be more specific about your goals.

**Comment by bilby91** [comment]
I'm sorry, didn't explain too much.

I was not talking about mapping a simple array of numbers, I was talking about mapping the ids with objects of a has many relation of core data. 

Basically what this mapping will do is, if there is an object with that id in the managed object context, add it to the relation, if not, create one with the given id and add it to the relation.

RESTKit has an API for this, you probably know what I'm talking about but here is the reference:
https://github.com/RestKit/RestKit/wiki/Object-Mapping#connecting-non-nested-relationships-using-foreign-keys

Can we open this again ?

Thanks!

**Comment by DenHeadless** [comment]
I haven't worked with this kind of API, but i think you can try simple hasMany mapping, if array of your id's has the same mapping for primary keys. EasyMapping uses find-or-create pattern for CoreData import, so it should work.

If not, you can always use mapKeyPath:toProperty:withValueBlock: and set all relations by yourself.

**Comment by bilby91** [comment]
@DenHeadless How would it look ? 

Let's say I have a a class product with a core data relation of has many with categories. The category_ids values are the id's of the categories.

**Comment by DenHeadless** [comment]
Something like this

```objective-c
[mapping mapKeyPath:@"categories" toProperty:@"categories" withValueBlock:^id(NSString * key, id value, NSManagedObjectContext * context) {
  for (NSNumber * categoryId  in value) {
    // fetch category with categoryID, add it to array of categories
  } 

  // Return array of categories, which are now objects instead of simple id's
}];
```

**Comment by bilby91** [comment]
I guess that I was thinking of solving this in the custom mapping. I'll try this and post back.

**Comment by armandzwan** [comment]
@bilby91 How did you fix this? I'm having the same problem...

**Comment by bilby91** [comment]
I don't like my actual solution :(, it looks like this:

```
[mapping mapKeyPath:@"category_ids" toProperty:@"categories" withValueBlock:^id(NSString * key, id value, NSManagedObjectContext * context) {
      NSMutableSet *set = [NSMutableSet set];

      for (NSNumber * categoryId  in value) {

        TPCategory *category;
        if (!(category = [TPCategory MR_findFirstByAttribute:@"id" withValue:categoryId inContext:context])) {
          category = [TPCategory MR_createInContext:context];
          category.id = categoryId;
        }

        [set addObject:category];
      }

      return set;
    }];
```

I think it could be a good idea to add support for this in EasyMapping.

**Comment by brunobasas** [comment]
Found any solutions?

**Comment by armandzwan** [comment]
Haven't tried anything new yet. I connect nested objects "manually" now. Waaaaay slower, but it works.

**Comment by armandzwan** [comment]
Bumped into this again. Any progress on this?
