### ISSUE TITLE
EasyMapping processing on background thread

### ISSUE THREAD

**Issue by mitrenegade** [EasyMapping/EasyMapping#96]
I am using EasyMapping to process a relatively large JSON and it seems to be slowing down the main thread slightly. An activity indicator animation we use visibly slows down, and I'm 90% sure it is because of processing the JSON on the main thread. 

I tried to use dispatch_async to run easymapping on a background thread with a child MOC, but I then get a multithread violation. It seems to happen in EKCoreDataImporter:fetchExistingObjectsForMapping:

    NSArray * existingObjects = [self.context executeFetchRequest:fetchRequest error:NULL];

Has any work been done to run EasyMapping on a background thread? Or should EasyMapping be fast enough on the main thread?

**Comment by DenHeadless** [comment]
First of all, EasyMapping should be fast enough to operate on a main thread. But moving parsing to background can be done easily.

Remember, that managed object contexts are not thread-safe, so you need to create an instance of NSManagedObjectContext per thread. I found that lazily creating them and storing them on NSThread thread dictionary is an ok solution. EasyMapping will always use provided context, expecially in CoreDataImporter.

Another thing to keep in mind is that you need to merge all changes to your main thread's context. Good way to do that is to subscribe to NSManagedObjectContextObjectsDidChangeNotification. 

There are also some great articles on building your CoreData stack with parent and child context, here are some links

http://floriankugler.com/2013/04/02/the-concurrent-core-data-stack/
https://blog.codecentric.de/en/2014/11/concurrency-coredata/
https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/CoreData/Articles/cdConcurrency.html

Hope that helps!

**Comment by Sh1mor1nka** [comment]
@mitrenegade don't you have big memory usage while you creating NSManagedObjects?
