### ISSUE TITLE
Mapping Managed Objects exchangeable with NSObject

### ISSUE THREAD

**Issue by czaku** [EasyMapping/EasyMapping#99]
Hi,

I have an object @interface MyManagedObject : NSManagedObject <EKManagedMappingProtocol>
it implements + objectMapping method and provides mapping

Can I map the objects with [EKMapper arrayOfObjectsFromExternalRepresentation:... withMapping:...]
as normal NSObjects, not as Managed objects for cases when I don't need to store them in CoreData? Or do I have to create a completely separate MyObject that is not a managed object for that and implement the same + objectMapping method?

**Comment by DenHeadless** [comment]
I believe it's not possible, or at least not common having NSManagedObjects created without NSManagedObjectContext. You may not need CoreData storage, but you won't be able to use NSManagedObject properties in usual way in any case - they need to be declared as dynamic, and use CoreData built-in mechanisms to manage ivars.

So, you can try, but this behaviour is not supported by EasyMapping, and you probably should create separate NSObject subclasses, and probably move mapping code in separate helper class.
